FROM nginx:alpine
WORKDIR /usr/share/nginx/html
ADD ./public/ /usr/share/nginx/html/
# ADD etc/nginx/nginx.conf /etc/nginx/nginx.conf
# ADD etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
