name: Deploy to git page and uploaded to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # 设置Node.js版本为16

      - name: Install dependencies and build
        run: |
          cd Blog  # 切换到Blog目录
          npm install
          npm run build
      - name: Clone target repository
        run: |
          git clone https://github.com/0YHR0/0yhr0.github.io.git blog-deployment
        continue-on-error: false
  
      - name: Copy public folder to target repository
        run: |
          cp -r Blog/public blog-deployment/

      - name: Commit and push to target repo
        run: |
          cd blog-deployment
          git add .
          git commit -m "Update notes"
          git push origin main

      - name: Archive build output
        run: |
          cd Blog
          tar -czvf public.tar.gz public
        continue-on-error: false

      - name: Extract version number from package.json
        id: version
        run: |
          cd Blog
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          cd Blog
          docker build -t 0yhr0/blog:${{ env.VERSION }} .
        env:
          DOCKER_BUILDKIT: 1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push 0yhr0/blog:${{ env.VERSION }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          draft: false
          prerelease: false
          files: Blog/public.tar.gz  # 指定压缩文件的正确路径
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: Blog/public
